using System;
using System.Collections.Generic;
using System.Linq;
using System.Text.RegularExpressions;

namespace RandomSongPicker
{
	public class SongDatabase
	{
		private readonly List<Song> _songs = new List<Song>();

		public SongDatabase()
		{
			var data = @"
A Child's Prayer (#12)
A Happy Family (#198)
A Happy Helper (#197)
A Prayer (#22)
A Prayer Song (#22)
A Smile Is like the Sunshine (#267)
A song is a wonderful kind of thing (#252)
A Song of Thanks (#20)
A Special Gift Is Kindness (#145)
A Young Man Prepared (#166)
Adam was a prophet, first one that we know (#110)
All over the world at the end of day (#16)
All Things Bright and Beautiful (#231)
An angel came to Joseph Smith (#86)
An Angel Came to Joseph Smith (#86)
As I have loved you (#136)
As I take the water and bread (#72)
At night, when I'm alone in bed (#11)
Autumn Day (#247)
Away in a Manger (#42)
Baptism (#100)
Be Happy! (#265)
Beautiful Savior (Crusader's Hymn) (#62)
Beauty Everywhere (#232)
Because God Loves Me (#234)
Because It's Spring (#239)
Before I Take the Sacrament (#73)
Birds in the Tree (#241)
Book of Mormon Stories (#118)
Busy as a man can be (#135)
Called to Serve (#174)
Can a Little Child like Me? (#9)
Children All Over the World (#16)
Choose the Right Way (#160)
Christmas Bells (#54)
Come with Me to Primary (Round) (#255)
Covered Wagons (#221)
Daddy's Homecoming (#210)
Dare to Do Right (#158)
Day after day the wagons are rolling (#221)
Dearest Mother, I Love You (#206)
Did Jesus Really Live Again? (#64)
Do As I'm Doing (#276)
Ducks in the pond quack a happy song (#264)
Early to bed and early to rise (#280)
Easter Hosanna (#68)
Ev'ry star is diff'rent (#142)
Every Star Is Different (#142)
Fair is the sunshine (#62)
Faith (#96)
Falling Snow (#248)
Fam'ly history - I am doing it (#94)
Families Can Be Together Forever (#188)
Family History - I Am Doing It (#94)
Family Night (#195)
Family Prayer (#189)
Father in Heaven, on this lovely day (#22)
Father Up Above (#23)
Father, I Will Reverent Be (#29)
Father, please hear us sing (#10)
Father, We Thank Thee for the Night (#8)
Fathers (#209)
Feliz Cumpleaños (#282)
First and second books of Nephi (#119)
Follow the Prophet (#110)
For Health and Strength (Round) (#21)
For Thy Bounteous Blessings (Round) (#21)
Friends Are Fun (#262)
Fun to Do (#253)
Genesis, Exodus, Leviticus, Numbers (#114)
Go the Second Mile (#167)
God Is Watching Over All (#229)
God planned the day (#234)
God's Love (#97)
Grandmother (#200)
Had I Been a Child (#80)
Happy Song (#264)
Happy, Happy Birthday (#284)
Have a Very Happy Birthday! (#284)
Have a Very Merry Christmas! (#51)
He Died That We Might Live Again (#65)
He Sent His Son (#34)
Head, Shoulders, Knees, and Toes (#275)
Healthy, Wealthy, and Wise (Round) (#280)
Heavenly Father, are you really there? (#12)
Heavenly Father, Now I Pray (#19)
Heavenly Father, While I Pray (#23)
Hello Song (#260)
Hello, Friends! (#254)
Help Me, Dear Father (#99)
Help Us, O God, to Understand (#73)
Here comes the oxcart, oh, how slow (#219)
Here We Are Together (#261)
Hinges (#277)
Home (#192)
Hosanna (#66)
How could the Father tell the world of love and tenderness? (#34)
How Dear to God Are Little Children (Appropriate for Parents and Leaders) (#180)
How Will They Know? (Appropriate for Parents and Leaders) (#182)
Hum Your Favorite Hymn (#152)
I always have a happy feeling (#157)
I Am a Child of God (#2)
I Am Glad for Many Things (#151)
I Am like a Star (#163)
I Believe in Being Honest (#149)
I belong to The Church of Jesus Christ of Latter-day Saints. (#77)
I Feel My Savior's Love (#74)
I have a fam'ly here on earth. (#188)
I Have a Family Tree (#199)
I Have Two Ears (#269)
I have two happy little feet (#270)
I Have Two Little Hands (#272)
I Hope They Call Me on a Mission (#169)
I kneel to pray ev'ry day (#14)
I know a name, a glorious name (#208)
I Know My Father Lives (#5)
I know you, and you know me. (#263)
I Like My Birthdays (#104)
I like to look for rainbows whenever there is rain (#103)
I Lived in Heaven (#4)
I looked out the window, and what did I see? (#242)
I Love to Pray (#25)
I love to read the holy scriptures (#109)
I Love to See the Temple (#95)
I Need My Heavenly Father (#18)
I Often Go Walking (#202)
I Pledge Myself to Love the Right (#161)
I Pray in Faith (#14)
I see my mother kneeling with our family each day. (#190)
I Thank Thee, Dear Father (#7)
I Think the World Is Glorious (#230)
I Think When I Read That Sweet Story (#56)
I Want to Be a Missionary Now (#168)
I Want to Be Reverent (#28)
I Want to Give the Lord My Tenth (#150)
I Want to Live the Gospel (#148)
I Wiggle (#271)
I Will Be Valiant (#162)
I Will Follow God's Plan (#164)
I will stand up when ""stand up"" is said (#278)
I Will Try to Be Reverent (#28)
I wonder, when he comes again (#82)
I'll seek the Lord early while in my youth (#108)
I'll Walk with You (#140)
I'm all made of hinges, 'cause ev'rything bends (#277)
I'm Glad to Pay a Tithing (#150)
I'm much too young to go abroad (#170)
I'm so glad when daddy comes home (#210)
I'm Thankful to Be Me (#11)
I'm Trying to Be like Jesus (#78)
If on occasion you have found(#152)
If with All Your Hearts(#15)
If you don't walk as most people do (#140)
If You're Happy (#266)
In the Leafy Treetops(#240)
In the morning when I wake(#25)
It is fun to have a friend who will play with you. (#262)
It shouldn't be hard to sit very still (#71)
It's always fun when grandpa comes (#201)
It's Autumntime (#246)
Jesus came to John the Baptist (#100)
Jesus entered Jordan's waters (#76)
Jesus Has Risen (#70)
Jesus Is Our Loving Friend (#58)
Jesus Loved the Little Children (#59)
Jesus Once Was a Little Child (#55)
Jesus Said Love Everyone (#61)
Jesus Wants Me for a Sunbeam (#60)
Keep the Commandments (#146)
Kindness Begins with Me (#145)
Latter-day Prophets (#134)
Let us gather in a circle (#189)
Lift Up Your Voice and Sing (#252)
Like sunshine in the morning that wakens day from night (#203)
Listen to the still small voice (#107)
Listen, Listen (Round) (#107)
Little Jesus (#39)
Little Lambs So White and Fair (#58)
Little Pioneer Children (Round) (#216)
Little Purple Pansies (#244)
Little Seeds Lie Fast Asleep (#243)
Love Is Spoken Here (#190)
Love One Another (#136)
Lullaby, lullaby, my little one. (#44)
Mary's Lullaby (#44)
Matthew, Mark, Luke, John, the Acts and Romans (#116)
Mother Dear (#206)
Mother, I Love You (#207)
Mother, Tell Me the Story (#204)
My Country (#224)
My Dad (#211)
My Flag, My Flag (#225)
My Hands (#273)
My Heavenly Father Loves Me (#228)
My life is a gift (#164)
My light is but a little one (#144)
My Mother Dear (#203)
Nephi's Courage (#120)
O Father, look on us today (#23)
Oh, come with me to Primary (#255)
Oh, How We Love to Stand (#279)
Oh, Hush Thee, My Baby (#48)
Oh, What Do You Do in the Summertime? (#245)
On a Golden Springtime (#88)
Once There Was a Snowman (#249)
Once within a Lowly Stable (#41)
Our Bishop (#135)
Our Chapel Is a Sacred Place (#30)
Our Door Is Always Open (Round) (#254)
Our Primary Colors (#258)
Our prophet has some words for you (#159)
Over the winding trail forward we go (#217)
Picture a Christmas (#50)
Pioneer Children Sang As They Walked (#214)
Pioneer Children Were Quick to Obey (#215)
Popcorn Popping (#242)
Quickly I'll Obey (#197)
Rain Is Falling All Around (#241)
Remember the Sabbath Day (#155)
Repentance (#98)
Rev'rence is more than just quietly sitting: (#31)
Reverence (#27)
Reverence Is Love (#31)
Reverently, Quietly (#26)
Roll Your Hands (#274)
Said Samuel, ""Within five years""(#36)
Samuel Tells of the Baby Jesus(#36)
Saturday(#196)
Search, Ponder, and Pray(#109)
Seek the Lord Early(#108)
Shine On(#144)
Sing a Song(Round)(#253)
Sing Your Way Home(#193)
Skies are fair above us(#232)
Sleep, Little Jesus(#47)
Smiles(#267)
Springtime Is Coming(#238)
Stand for the Right (#159)
Stand Up(#278)
Stars Were Gleaming(#37)
Teach Me to Walk in the Light (#177)
Teacher, Do You Love Me? (#178)
Tell Me the Stories of Jesus (#57)
Tell Me, Dear Lord (#176)
Thank Thee for Everything (#10)
Thank thee for the world so sweet (#20)
Thank Thee, Father (#24)
Thanks to Our Father (#20)
Thanks to Thee (#6)
The Books in the Book of Mormon (#119)
The Books in the New Testament (#116)
The Books in the Old Testament (#114)
The Chapel Doors (#156)
The Church of Jesus Christ (#77)
The Commandments (#112)
The Dearest Names (#208)
The Eighth Article of Faith (#127)
The Eleventh Article of Faith (#130)
The Family (#194)
The father of our home leads our family (#209)
The Fifth Article of Faith (#125)
The First Article of Faith (#122)
The Fourth Article of Faith (#124)
The Golden Plates (#86)
The Golden Plates lay hidden (#86)
The Handcart Song (#220)
The Hearts of the Children (#92)
The hearts of the children have turned to their fathers (#90)
The Holy Ghost (#105)
The Lord commanded Nephi to go and get the plates (#120)
The Lord Gave Me a Temple (#153)
The Lord needs valiant servants (#162)
The Nativity Song (#52)
The Ninth Article of Faith (#128)
The Oxcart (#219)
The Priesthood Is Restored (#89)
The prophecies of long ago were now at last fulfilled (#68)
The Prophet Said to Plant a Garden (#237)
The Sacrament (#72)
The Sacred Grove (#87)
The Second Article of Faith (#122)
The Seventh Article of Faith (#126)
The Shepherd's Carol (Round) (#40)
The Sixth Article of Faith (#126)
The Still Small Voice (#106)
The Tenth Article of Faith (#128)
The Things I Do (#170)
The Third Article of Faith (#123)
The Thirteenth Article of Faith (#132)
The Twelfth Article of Faith (#131)
The Wise Man and the Foolish Man (#281)
The Word of Wisdom (#154)
The World Is So Big (#235)
The World Is So Lovely (#233)
There Was Starlight on the Hillside (#40)
There's a right way to live and be happy (#160)
This Is God's House (#30)
This Is My Beloved Son (#76)
This is my country (#224)
This is the night we've waited for (#195)
This is the season beloved of the year. (#52)
This month is such a special one (#283)
Thou shalt have no gods but Me. (#112)
Though a boy I may appear (#166)
Through a still small voice, the Spirit speaks to me (#106)
To Be a Pioneer (#218)
To Get Quiet (#275)
To Think about Jesus (#71)
Today, dear Father, I will show (#27)
Truth from Elijah (#90)
Two Happy Feet (#270)
Two Little Eyes (#268)
We Are Different (#263)
We Are Reverent (#27)
We believe all that God has revealed (#128)
We believe in being honest, true, chaste, benevolent (#132)
We believe in being subject to kings (#131)
We believe in God, the Eternal Father (#122)
We believe in the gift of tongues, prophecy, revelation, visions (#126)
We believe in the literal gathering of Israel (#128)
We believe in the same organization that existed in the Primitive Church (#126)
We believe that a man must be called of God (#125)
We believe that men will be punished for their own sins (#122)
We believe that the first principles and ordinances of the Gospel are: (#124)
We believe that through the Atonement of Christ (#123)
We believe the Bible to be the word of God (#127)
We Bow Our Heads (#25)
We bow our heads in prayer today (#22)
We claim the priv'lege of worshiping Almighty God (#130)
We do not see the wind (#97)
We have been born, as Nephi of old (#172)
We Welcome You (#256)
We'll Bring the World His Truth (Army of Helaman) (#172)
We're All Together Again (#259)
Westward Ho! (#217)
When Christ was on the earth (#105)
When Grandpa Comes (#201)
When He Comes Again (#82)
When I Am Baptized (#103)
When I Go to Church (#157)
When I'm home or far away (#6)
When Jesus Christ Was Baptized (#102)
When Joseph Went to Bethlehem (#38)
When pioneers moved to the West (#220)
When the fam'ly gets together, after evening work is done (#194)
When there is a task to do, do it with a smile (#167)
When We're Helping (#198)
Whenever I hear the song of a bird (#228)
Whenever I Think about Pioneers (#222)
Where Love Is (#138)
Who Is the Child? (#46)
Why is the sky so blue and clear? (#239)
You don't have to push a handcart (#218)
You give me a kiss (#200)
You've Had a Birthday (Round) (#285)
Your Happy Birthday (#283)";

			ProcessData(data);
		}

		private void ProcessData(string text)
		{
			var lines = text.Split(new[] { Environment.NewLine }, StringSplitOptions.RemoveEmptyEntries);
			foreach (var line in lines)
			{
				var match = Regex.Match(line, @"^(.+) \(#(\d+)\)$");

				if (match.Success)
				{
					var title = match.Groups[1].Value;
					var page = Convert.ToInt32(match.Groups[2].Value);
					_songs.Add(new Song(title, page));
				}
			}
		}

		public List<Song> Search(string str)
		{
			return _songs
				.Where(s => s.Name.ToUpper().StartsWith(str.ToUpper()))
				.Union(_songs.Where(s => s.Name.ToUpper().Contains(str.ToUpper())))
				.ToList();
		}
	}
}